# Generated by Django 4.0.4 on 2022-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodmodel',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
