# Generated by Django 4.0.4 on 2022-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_brand_product_prodcode_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(default='New', max_length=50, verbose_name='Make'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodmodel',
            field=models.CharField(default='Null', max_length=50, verbose_name='Model'),
        ),
    ]
