# Generated by Django 4.0.4 on 2022-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_make_product_state_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drive',
            field=models.CharField(choices=[('All Wheel Drive(AWD)', 'All Wheel Drive(AWD)'), ('Front Wheel Drive(FWD)', 'Front Wheel Drive(FWD)'), ('Rear Wheel Drive(RWD)', 'Rear Wheel Drive(RWD)'), ('4 Wheel Drive(4WD)', '4 Wheel Drive(4WD)')], default='Front Wheel Drive(FWD)', max_length=25, verbose_name='Drive'),
        ),
    ]
