# Generated by Django 4.0.4 on 2022-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_fuel_product_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine_size',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
    ]
