# Generated by Django 4.0.4 on 2022-04-26 18:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_engine_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='bodycolor',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='doors',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Doors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type',
            field=models.CharField(default=1.0, max_length=70, verbose_name='Engine Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4, verbose_name='Fuel Consumption/km'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Manufacture Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Mileage'),
        ),
        migrations.AddField(
            model_name='product',
            name='regdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seats',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Seats'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_size',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3, verbose_name='Engine Size(Ltrs)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=0.0, validators=[django.core.validators.MaxValueValidator(500000000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500000000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Quantity'),
        ),
    ]
